name: 'complex serial workflow demo'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci-build-all:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build website
      run: sleep 30
    - name: Build payment service
      run: sleep 30  
    - name: Build inventory service
      run: sleep 30  
  ci-test-all:
    runs-on: ubuntu-latest
    needs: [ci-build-all]
    steps:
    - uses: actions/checkout@v3
    - name: test website
      run: sleep 30 
    - name: test payment service
      run: sleep 30   
    - name: test inventory service
      run: sleep 30  
  cd-deploy-all:
    runs-on: ubuntu-latest
    needs: [ci-test-all]
    steps:
    - uses: actions/checkout@v3
    - name: deploy website
      run: sleep 30
    - name: deploy payment service
      run: sleep 30
    - name: deploy inventory service
      run: sleep 30
  cd-smoketest:
    runs-on: ubuntu-latest
    needs: [cd-deploy-all]
    steps:
    - name: run smoke tests
      run: sleep 30

