name: 'complex parallel workflow demo'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci-website:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build website
      run: sleep 30
    - name: test website
      run: sleep 30 
  ci-payment-service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build payment service
      run: sleep 30 
    - name: test payment service
      run: sleep 30 
  ci-inventory-service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build inventory service
      run: sleep 30 
    - name: test inventory service
      run: sleep 30 
      
  cd-deploy-website:
    runs-on: ubuntu-latest
    needs: [ci-website, ci-payment-service, ci-inventory-service]
    steps:
    - uses: actions/checkout@v3
    - name: deploy website
      run: sleep 30
  cd-deploy-payment-service:
    runs-on: ubuntu-latest
    needs: [ci-website, ci-payment-service, ci-inventory-service]
    steps:
    - uses: actions/checkout@v3
    - name: deploy payment service
      run: sleep 30
  cd-deploy-inventory-service:
    runs-on: ubuntu-latest
    needs: [ci-website, ci-payment-service, ci-inventory-service]
    steps:
    - uses: actions/checkout@v3
    - name: deploy inventory service
      run: sleep 30
      
  cd-smoketest:
    runs-on: ubuntu-latest
    needs: [cd-deploy-website, cd-deploy-payment-service, cd-deploy-inventory-service]
    steps:
    - name: run smoke tests
      run: sleep 30

