name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Build web service
      run: dotnet build src/WebService/WebService.csproj
    - name: Build website
      run: dotnet build src/WebService/WebService.csproj        
  buildDatabase:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download the build artifacts
      uses: actions/download-artifact@v3
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Build database project
      run: msbuild 'src/SamSmithNZ.Database/Database.sqlproj' /p:configuration='Release' /p:platform='Any CPU'         
    - name: check directory
      run: dir "${{ github.workspace }}\src\Database\bin\Output"         
    - name: 'Copy database files to artifacts folder'
      run: |
        mkdir "${{ github.workspace }}\Database" 
        Copy-Item -Path "${{ github.workspace }}\src\Database\bin\Output\SamSmithNZ.Database.dacpac" -Destination "${{ github.workspace }}\Database"         
    - name: check directory
      run: dir "${{ github.workspace }}/Database"
    - name: Publish database objects
      uses: actions/upload-artifact@v3
      with:
        name: database
        path: ${{ github.workspace }}/Database
  
  test:
    runs-on: ubuntu-latest
    needs: [build, buildDatabase]
    steps:
    - uses: actions/checkout@v3
    - name: Unit Tests
      run: dotnet test src/UnitTests/UnitTests.csproj
    - name: Integration tests
      run: dotnet test src/IntegrationTests/IntegrationTests.csproj
    - name: End to end tests
      run: dotnet test src/EndToEndTests/EndToEndTests.csproj
