name: 'Parallel workflow demo'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build web service
      run: sleep 5
    - name: Build website
      run: sleep 5  
  test:
    runs-on: ubuntu-latest
    needs: [build] 
    steps:
    - uses: actions/checkout@v3
    - name: run Unit Tests
      run: sleep 5 
    - name: run Integration tests
      run: sleep 5   
  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@v3
    - name: deploying web service
      run: sleep 5
    - name: deploying website
      run: sleep 5
    - name: run smoke tests
      run: sleep 5
    - name: switch blue/green
      run: sleep 5
